name: docker-build-push

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Extract branch name
        run: echo "RELEASE_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: |-
            linux/amd64
            linux/arm64
          build-args: |
            VERSION=${{ env.RELEASE_VERSION }}
          tags: |
            moriony/syncthing-relaysrv:latest
            moriony/syncthing-relaysrv:${{ env.RELEASE_VERSION }}
            ghcr.io/moriony/syncthing-relaysrv:latest
            ghcr.io/moriony/syncthing-relaysrv:${{ env.RELEASE_VERSION }}
